### ISSUE TITLE
Handling of PRUs in kernel module

### ISSUE THREAD

**Issue by geissdoerfer** [geissdoerfer/shepherd#7]
Currently, the kernel module polls for the PRUs by trying a range of phandles during initialization. This is an ugly workaround and may not work under all circumstances. Instead, the shepherd kernel module should be registered as a platform driver for the PRUs and automatically probed, once the PRUs are detected by the kernel.

**Comment by kugelbit** [comment]
Thanks for filling the Issue.

We can get rid of this "ugly workaround" by writing a platform-driver-kernel-modul. I will go deeper into this in the next few weeks.
